<?php
namespace taktwerk\swisstransport\widgets;

use yii\bootstrap\Widget;
use taktwerk\swisstransport\components\Connection;

class DepartureWidget extends Widget
{

    private $lines;

    public function init()
    {
        parent::init();
        $connection = new Connection();
        $this->lines = $connection->getNext();
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $output = '<div class="col-sm-12">';
        $output .= '<h4>' . \Yii::t('app','Bus Lines') . '</h4>';


        foreach ($this->lines as $bus => $line) {
            $output .= '<div class="row">';
            $output .= '<div class="col-sm-12">';
            $output .= $line['from'] . ', ' . $bus;
            $output .= '</div>';

            foreach ($line['to'] as $to => $departure) {
                $output .= '<div class="col-sm-3 col-sm-offset-1">';
                $output .= $to;
                $output .= '</div>';
                $output .= '<div class="col-sm-8">';
                $output .= $departure;
                $output .= '</div>';

            }
            $output .= '</div>';
        }
        $output .= '</div>';
        return $output;
    }
}
